export interface Product {
  id: string
  name: string
  slug: string
  description: string
  price: number
  originalPrice?: number
  category: string
  subcategory?: string
  images: string[]
  features: string[]
  dimensions: {
    width: number
    height: number
    depth: number
    unit: string
  }
  materials: string[]
  colors: string[]
  inStock: boolean
  isNew?: boolean
  isFeatured?: boolean
  rating: number
  reviewCount: number
}

export interface Category {
  id: string
  name: string
  slug: string
  description: string
  image: string
  productCount: number
  subcategories?: string[]
}

export const categories: Category[] = [
  {
    id: "living-room",
    name: "Living Room",
    slug: "living-room",
    description: "Contemporary comfort meets sophisticated design",
    image: "https://i.pinimg.com/736x/2c/37/9d/2c379d744dc672c07a0cb199bf5cdb3a.jpg",
    productCount: 24,
    subcategories: ["Sofas", "Coffee Tables", "TV Units", "Armchairs", "Side Tables"],
  },
  {
    id: "bedroom",
    name: "Bedroom",
    slug: "bedroom",
    description: "Serene sanctuaries for restful nights",
    image: "/elegant-bedroom.png",
    productCount: 18,
    subcategories: ["Beds", "Wardrobes", "Nightstands", "Dressers", "Mirrors"],
  },
  {
    id: "dining",
    name: "Dining",
    slug: "dining",
    description: "Elegant gatherings around exquisite tables",
    image: "/sophisticated-dining-set.png",
    productCount: 15,
    subcategories: ["Dining Tables", "Dining Chairs", "Bar Stools", "Sideboards", "Display Cabinets"],
  },
  {
    id: "office",
    name: "Office",
    slug: "office",
    description: "Executive spaces that inspire productivity",
    image: "/premium-office-setup.png",
    productCount: 12,
    subcategories: ["Desks", "Office Chairs", "Bookcases", "Filing Cabinets", "Meeting Tables"],
  },
  {
    id: "storage",
    name: "Storage",
    slug: "storage",
    description: "Organized beauty meets functional design",
    image: "/luxury-wardrobe-storage.png",
    productCount: 8,
    subcategories: ["Wardrobes", "Chests", "Shelving", "Cabinets", "Storage Benches"],
  },
  {
    id: "accessories",
    name: "Accessories",
    slug: "accessories",
    description: "Finishing touches that complete your space",
    image: "/premium-home-decor.png",
    productCount: 32,
    subcategories: ["Lighting", "Rugs", "Artwork", "Decorative Objects", "Mirrors"],
  },
]

export const products: Product[] = [
  // Living Room Products
  {
    id: "luxe-sectional-sofa",
    name: "Luxe Sectional Sofa",
    slug: "luxe-sectional-sofa",
    description:
      "A masterpiece of contemporary design featuring premium Italian leather and solid hardwood frame. This sectional offers unparalleled comfort with deep seating and plush cushions.",
    price: 4299,
    originalPrice: 4999,
    category: "living-room",
    subcategory: "Sofas",
    images: ["/luxury-sectional-sofa.png", "/sectional-sofa-detail.png"],
    features: [
      "Premium Italian Leather",
      "Solid Hardwood Frame",
      "Deep Seating",
      "Reversible Chaise",
      "Lifetime Warranty",
    ],
    dimensions: { width: 120, height: 32, depth: 40, unit: "inches" },
    materials: ["Italian Leather", "Hardwood", "High-Density Foam"],
    colors: ["Charcoal", "Cognac", "Ivory"],
    inStock: true,
    isFeatured: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 127,
  },
  {
    id: "marble-coffee-table",
    name: "Carrara Marble Coffee Table",
    slug: "carrara-marble-coffee-table",
    description:
      "Elegant coffee table featuring genuine Carrara marble top with distinctive veining, supported by a sleek brushed steel base.",
    price: 1899,
    category: "living-room",
    subcategory: "Coffee Tables",
    images: ["/marble-coffee-table.png", "/placeholder-hc4os.png"],
    features: ["Genuine Carrara Marble", "Brushed Steel Base", "Unique Veining Pattern", "Protective Coating"],
    dimensions: { width: 48, height: 16, depth: 24, unit: "inches" },
    materials: ["Carrara Marble", "Brushed Steel"],
    colors: ["White Marble", "Black Marble"],
    inStock: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 89,
  },
  {
    id: "executive-armchair",
    name: "Executive Leather Armchair",
    slug: "executive-leather-armchair",
    description:
      "Sophisticated armchair crafted from top-grain leather with ergonomic design and solid walnut wood accents.",
    price: 2199,
    category: "living-room",
    subcategory: "Armchairs",
    images: ["/executive-leather-armchair.png"],
    features: ["Top-Grain Leather", "Ergonomic Design", "Walnut Wood Accents", "360° Swivel"],
    dimensions: { width: 32, height: 42, depth: 34, unit: "inches" },
    materials: ["Top-Grain Leather", "Walnut Wood", "Steel Frame"],
    colors: ["Black", "Brown", "Navy"],
    inStock: true,
    rating: 4.7,
    reviewCount: 64,
  },
  {
    id: "velvet-chesterfield-sofa",
    name: "Velvet Chesterfield Sofa",
    slug: "velvet-chesterfield-sofa",
    description: "Classic Chesterfield design reimagined in luxurious velvet with deep button tufting and rolled arms.",
    price: 3599,
    originalPrice: 3999,
    category: "living-room",
    subcategory: "Sofas",
    images: ["/luxury-velvet-chesterfield.png"],
    features: ["Deep Button Tufting", "Rolled Arms", "Kiln-Dried Hardwood", "Premium Velvet"],
    dimensions: { width: 84, height: 32, depth: 38, unit: "inches" },
    materials: ["Velvet", "Hardwood", "Brass Nailheads"],
    colors: ["Emerald Green", "Navy Blue", "Burgundy", "Charcoal"],
    inStock: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 156,
  },
  {
    id: "glass-coffee-table-round",
    name: "Round Glass Coffee Table",
    slug: "round-glass-coffee-table",
    description: "Contemporary round coffee table with tempered glass top and sculptural metal base.",
    price: 1299,
    category: "living-room",
    subcategory: "Coffee Tables",
    images: ["/modern-glass-coffee-table.png"],
    features: ["Tempered Glass", "Sculptural Base", "Easy to Clean", "Space-Saving Design"],
    dimensions: { width: 42, height: 16, depth: 42, unit: "inches" },
    materials: ["Tempered Glass", "Brushed Steel"],
    colors: ["Clear Glass", "Smoked Glass"],
    inStock: true,
    rating: 4.6,
    reviewCount: 73,
  },
  {
    id: "mid-century-tv-unit",
    name: "Mid-Century TV Unit",
    slug: "mid-century-tv-unit",
    description: "Sleek TV unit with sliding doors, cable management, and authentic mid-century design elements.",
    price: 1799,
    category: "living-room",
    subcategory: "TV Units",
    images: ["/mid-century-modern-tv-unit-walnut.png"],
    features: ["Sliding Doors", "Cable Management", "Adjustable Shelves", "Tapered Legs"],
    dimensions: { width: 72, height: 24, depth: 18, unit: "inches" },
    materials: ["Walnut Veneer", "Solid Wood"],
    colors: ["Walnut", "Teak", "Oak"],
    inStock: true,
    isNew: true,
    rating: 4.7,
    reviewCount: 92,
  },
  {
    id: "accent-side-table",
    name: "Marble Accent Side Table",
    slug: "marble-accent-side-table",
    description: "Elegant side table featuring white marble top with gold-finished metal legs.",
    price: 599,
    category: "living-room",
    subcategory: "Side Tables",
    images: ["https://handicraftstown.com/cdn/shop/files/delaney-18-hexagon-marble-accent-table-o.jpg?v=1688459975"],
    features: ["White Marble Top", "Gold Metal Legs", "Compact Design", "Versatile Styling"],
    dimensions: { width: 20, height: 22, depth: 20, unit: "inches" },
    materials: ["White Marble", "Gold-Plated Steel"],
    colors: ["White Marble/Gold", "Black Marble/Brass"],
    inStock: true,
    rating: 4.5,
    reviewCount: 48,
  },

  // Bedroom Products
  {
    id: "platform-bed-king",
    name: "Modern Platform Bed - King",
    slug: "modern-platform-bed-king",
    description:
      "Minimalist platform bed with clean lines and integrated nightstands. Crafted from sustainable oak with a natural finish.",
    price: 2799,
    category: "bedroom",
    subcategory: "Beds",
    images: ["/modern-king-platform-bed.png"],
    features: ["Integrated Nightstands", "Sustainable Oak", "Low Profile Design", "Hidden Storage"],
    dimensions: { width: 80, height: 32, depth: 84, unit: "inches" },
    materials: ["Oak Wood", "Natural Finish"],
    colors: ["Natural Oak", "Walnut", "White Oak"],
    inStock: true,
    isNew: true,
    rating: 4.6,
    reviewCount: 43,
  },
  {
    id: "luxury-wardrobe",
    name: "Luxury Walk-in Wardrobe",
    slug: "luxury-walk-in-wardrobe",
    description:
      "Spacious wardrobe system with soft-close doors, LED lighting, and customizable interior organization.",
    price: 5499,
    category: "bedroom",
    subcategory: "Wardrobes",
    images: ["/luxury-wardrobe-system.png"],
    features: ["Soft-Close Doors", "LED Lighting", "Customizable Interior", "Mirror Panels"],
    dimensions: { width: 96, height: 84, depth: 24, unit: "inches" },
    materials: ["Engineered Wood", "Mirror", "LED Strips"],
    colors: ["White Gloss", "Charcoal", "Natural Wood"],
    inStock: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 76,
  },
  {
    id: "upholstered-queen-bed",
    name: "Upholstered Queen Bed",
    slug: "upholstered-queen-bed",
    description: "Luxurious upholstered bed with wingback headboard and nail head trim details.",
    price: 2299,
    category: "bedroom",
    subcategory: "Beds",
    images: ["/upholstered-queen-bed-wingback-headboard.png"],
    features: ["Wingback Headboard", "Nail Head Trim", "Premium Upholstery", "Solid Wood Frame"],
    dimensions: { width: 64, height: 54, depth: 84, unit: "inches" },
    materials: ["Premium Fabric", "Solid Wood", "High-Density Foam"],
    colors: ["Light Gray", "Navy Blue", "Cream", "Charcoal"],
    inStock: true,
    rating: 4.7,
    reviewCount: 134,
  },
  {
    id: "floating-nightstand",
    name: "Floating Nightstand",
    slug: "floating-nightstand",
    description: "Space-saving floating nightstand with hidden drawer and wireless charging pad.",
    price: 399,
    category: "bedroom",
    subcategory: "Nightstands",
    images: ["/floating-nightstand-wireless-charging.png"],
    features: ["Wall-Mounted", "Hidden Drawer", "Wireless Charging", "LED Accent Light"],
    dimensions: { width: 24, height: 6, depth: 12, unit: "inches" },
    materials: ["Oak Veneer", "Wireless Charging Pad"],
    colors: ["White Oak", "Walnut", "Black Oak"],
    inStock: true,
    isNew: true,
    rating: 4.6,
    reviewCount: 67,
  },
  {
    id: "vintage-dresser",
    name: "Vintage-Style Dresser",
    slug: "vintage-style-dresser",
    description: "Six-drawer dresser with vintage-inspired hardware and rich wood finish.",
    price: 1899,
    category: "bedroom",
    subcategory: "Dressers",
    images: ["/vintage-dresser-six-drawers.png"],
    features: ["Six Drawers", "Vintage Hardware", "Dovetail Joints", "Rich Wood Finish"],
    dimensions: { width: 60, height: 34, depth: 20, unit: "inches" },
    materials: ["Solid Wood", "Antique Brass Hardware"],
    colors: ["Rich Mahogany", "Antique White", "Weathered Oak"],
    inStock: true,
    rating: 4.8,
    reviewCount: 89,
  },

  // Dining Products
  {
    id: "dining-table-walnut",
    name: "Live Edge Walnut Dining Table",
    slug: "live-edge-walnut-dining-table",
    description:
      "Stunning live edge dining table crafted from a single piece of American walnut, showcasing natural wood grain and character.",
    price: 3299,
    category: "dining",
    subcategory: "Dining Tables",
    images: ["/live-edge-walnut-table.png"],
    features: ["Single Piece Walnut", "Live Edge Design", "Natural Wood Grain", "Steel Hairpin Legs"],
    dimensions: { width: 84, height: 30, depth: 42, unit: "inches" },
    materials: ["American Walnut", "Steel"],
    colors: ["Natural Walnut"],
    inStock: true,
    isFeatured: true,
    isNew: true,
    rating: 4.9,
    reviewCount: 52,
  },
  {
    id: "dining-chairs-set",
    name: "Upholstered Dining Chairs (Set of 4)",
    slug: "upholstered-dining-chairs-set",
    description:
      "Elegant dining chairs with premium fabric upholstery and solid oak legs. Designed for comfort and style.",
    price: 1599,
    category: "dining",
    subcategory: "Dining Chairs",
    images: ["/upholstered-dining-chairs.png"],
    features: ["Premium Fabric", "Solid Oak Legs", "Ergonomic Design", "Set of 4"],
    dimensions: { width: 20, height: 32, depth: 22, unit: "inches" },
    materials: ["Premium Fabric", "Oak Wood"],
    colors: ["Charcoal", "Cream", "Navy", "Forest Green"],
    inStock: true,
    rating: 4.7,
    reviewCount: 91,
  },
  {
    id: "extendable-dining-table",
    name: "Extendable Dining Table",
    slug: "extendable-dining-table",
    description: "Versatile dining table that extends from 6 to 10 seats with hidden leaf mechanism.",
    price: 2799,
    category: "dining",
    subcategory: "Dining Tables",
    images: ["/modern-extendable-dining-table.png"],
    features: ["Hidden Leaf Mechanism", "Seats 6-10", "Smooth Extension", "Solid Wood Construction"],
    dimensions: { width: 72, height: 30, depth: 42, unit: "inches" },
    materials: ["Solid Oak", "Steel Hardware"],
    colors: ["Natural Oak", "Espresso", "White Wash"],
    inStock: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 112,
  },
  {
    id: "bar-stools-set",
    name: "Industrial Bar Stools (Set of 2)",
    slug: "industrial-bar-stools-set",
    description: "Industrial-style bar stools with adjustable height and comfortable padded seats.",
    price: 899,
    category: "dining",
    subcategory: "Bar Stools",
    images: ["https://m.media-amazon.com/images/I/811tE3c9dhL._UF894,1000_QL80_.jpg"],
    features: ["Adjustable Height", "Padded Seats", "Industrial Design", "Set of 2"],
    dimensions: { width: 16, height: 42, depth: 16, unit: "inches" },
    materials: ["Steel Frame", "Faux Leather", "Rubber Footrest"],
    colors: ["Black", "Brown", "Gray"],
    inStock: true,
    rating: 4.5,
    reviewCount: 78,
  },
  {
    id: "sideboard-buffet",
    name: "Modern Sideboard Buffet",
    slug: "modern-sideboard-buffet",
    description: "Sleek sideboard with sliding doors, adjustable shelves, and wire management.",
    price: 1599,
    category: "dining",
    subcategory: "Sideboards",
    images: ["https://www.vikinterio.com/product-images/VIK_BUFF_0_1.jpg/473239000007054087/1100x1100"],
    features: ["Sliding Doors", "Adjustable Shelves", "Wire Management", "Soft-Close Hinges"],
    dimensions: { width: 72, height: 32, depth: 18, unit: "inches" },
    materials: ["Engineered Wood", "Metal Handles"],
    colors: ["White Gloss", "Walnut", "Black"],
    inStock: true,
    rating: 4.7,
    reviewCount: 95,
  },

  // Office Products
  {
    id: "executive-desk",
    name: "Executive Standing Desk",
    slug: "executive-standing-desk",
    description:
      "Height-adjustable executive desk with premium walnut veneer, integrated cable management, and whisper-quiet motors.",
    price: 2899,
    category: "office",
    subcategory: "Desks",
    images: ["/executive-standing-desk.png"],
    features: ["Height Adjustable", "Walnut Veneer", "Cable Management", "Whisper-Quiet Motors"],
    dimensions: { width: 72, height: 30, depth: 36, unit: "inches" },
    materials: ["Walnut Veneer", "Steel Frame"],
    colors: ["Walnut", "Black", "White"],
    inStock: true,
    isNew: true,
    rating: 4.8,
    reviewCount: 38,
  },
  {
    id: "ergonomic-office-chair",
    name: "Ergonomic Executive Chair",
    slug: "ergonomic-executive-chair",
    description: "Premium ergonomic chair with lumbar support, breathable mesh back, and Italian leather seat.",
    price: 1299,
    category: "office",
    subcategory: "Office Chairs",
    images: ["https://m.media-amazon.com/images/I/71aGX3PevYL.jpg"],
    features: ["Lumbar Support", "Breathable Mesh", "Italian Leather Seat", "Adjustable Arms"],
    dimensions: { width: 28, height: 48, depth: 28, unit: "inches" },
    materials: ["Italian Leather", "Mesh", "Aluminum"],
    colors: ["Black", "White", "Gray"],
    inStock: true,
    rating: 4.6,
    reviewCount: 124,
  },
  {
    id: "l-shaped-desk",
    name: "L-Shaped Executive Desk",
    slug: "l-shaped-executive-desk",
    description: "Spacious L-shaped desk with built-in filing cabinet and keyboard tray.",
    price: 1999,
    category: "office",
    subcategory: "Desks",
    images: ["https://ouchcart.com/cdn/shop/products/l-shape-study-table-in-white-colour-by-riyan-luxiwood-prte.png?v=1721375553"],
    features: ["L-Shaped Design", "Built-in Filing", "Keyboard Tray", "Cable Management"],
    dimensions: { width: 72, height: 30, depth: 60, unit: "inches" },
    materials: ["Engineered Wood", "Metal Hardware"],
    colors: ["Espresso", "White", "Gray"],
    inStock: true,
    rating: 4.6,
    reviewCount: 87,
  },
  {
    id: "bookcase-tall",
    name: "Tall Bookcase with Ladder",
    slug: "tall-bookcase-with-ladder",
    description: "Library-style tall bookcase with rolling ladder and adjustable shelves.",
    price: 2299,
    category: "office",
    subcategory: "Bookcases",
    images: ["https://preview.redd.it/lgr979ae6dg71.jpg?width=1080&crop=smart&auto=webp&s=56b325797fc63c548e8426e0eefd39afdc143f8e"],
    features: ["Rolling Ladder", "Adjustable Shelves", "Library Style", "Solid Wood"],
    dimensions: { width: 48, height: 96, depth: 12, unit: "inches" },
    materials: ["Solid Oak", "Steel Ladder"],
    colors: ["Natural Oak", "Dark Walnut", "White"],
    inStock: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 64,
  },

  // Storage Products
  {
    id: "modular-shelving",
    name: "Modular Shelving System",
    slug: "modular-shelving-system",
    description:
      "Versatile modular shelving system that can be configured to fit any space. Made from sustainable bamboo.",
    price: 899,
    category: "storage",
    subcategory: "Shelving",
    images: ["https://cdn20.pamono.com/p/g/1/9/1988526_z0cscp5vau/modular-wall-shelving-system-by-poul-cadovius-for-cado-1960s-10.jpg"],
    features: ["Modular Design", "Sustainable Bamboo", "Easy Assembly", "Multiple Configurations"],
    dimensions: { width: 48, height: 72, depth: 12, unit: "inches" },
    materials: ["Bamboo", "Steel Connectors"],
    colors: ["Natural Bamboo", "Dark Bamboo"],
    inStock: true,
    rating: 4.5,
    reviewCount: 67,
  },
  {
    id: "storage-ottoman",
    name: "Storage Ottoman Bench",
    slug: "storage-ottoman-bench",
    description: "Multi-functional ottoman with hidden storage and premium upholstery.",
    price: 499,
    category: "storage",
    subcategory: "Storage Benches",
    images: ["https://m.media-amazon.com/images/I/61nWKyAqGaL._UF894,1000_QL80_.jpg"],
    features: ["Hidden Storage", "Premium Upholstery", "Multi-Functional", "Sturdy Construction"],
    dimensions: { width: 48, height: 18, depth: 16, unit: "inches" },
    materials: ["Premium Fabric", "Solid Wood Frame"],
    colors: ["Gray", "Navy", "Beige", "Charcoal"],
    inStock: true,
    rating: 4.5,
    reviewCount: 92,
  },
  {
    id: "chest-of-drawers",
    name: "Five-Drawer Chest",
    slug: "five-drawer-chest",
    description: "Tall chest of drawers with soft-close mechanisms and elegant brass handles.",
    price: 1299,
    category: "storage",
    subcategory: "Chests",
    images: ["https://teaklab.com/wp-content/uploads/2019/10/Teaklab-Chest-of-Five-Drawers-2.jpg"],
    features: ["Five Drawers", "Soft-Close", "Brass Handles", "Anti-Tip Safety"],
    dimensions: { width: 32, height: 48, depth: 18, unit: "inches" },
    materials: ["Solid Wood", "Brass Hardware"],
    colors: ["Natural Wood", "White", "Black"],
    inStock: true,
    rating: 4.7,
    reviewCount: 76,
  },

  // Accessories Products
  {
    id: "designer-floor-lamp",
    name: "Designer Arc Floor Lamp",
    slug: "designer-arc-floor-lamp",
    description:
      "Sculptural arc floor lamp with adjustable height and dimmable LED lighting. Features a marble base for stability.",
    price: 699,
    category: "accessories",
    subcategory: "Lighting",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuUeGylGTw-YIPsmMfujjEuKeA_Cl5cIy-Gw&s"],
    features: ["Adjustable Height", "Dimmable LED", "Marble Base", "Sculptural Design"],
    dimensions: { width: 24, height: 84, depth: 24, unit: "inches" },
    materials: ["Brushed Steel", "Marble", "LED"],
    colors: ["Brushed Steel", "Matte Black", "Brass"],
    inStock: true,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 89,
  },
  {
    id: "handwoven-rug",
    name: "Handwoven Persian Rug",
    slug: "handwoven-persian-rug",
    description: "Authentic handwoven Persian rug with intricate patterns and rich colors. Made from premium wool.",
    price: 1899,
    category: "accessories",
    subcategory: "Rugs",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDlYwyVimi4tgcGzoRtMpishNolghI-CjCGA&s"],
    features: ["Handwoven", "Premium Wool", "Intricate Patterns", "Authentic Design"],
    dimensions: { width: 96, height: 1, depth: 132, unit: "inches" },
    materials: ["Premium Wool"],
    colors: ["Traditional Red", "Navy Blue", "Cream"],
    inStock: true,
    rating: 4.9,
    reviewCount: 45,
  },
  {
    id: "decorative-mirror",
    name: "Sunburst Decorative Mirror",
    slug: "sunburst-decorative-mirror",
    description: "Statement sunburst mirror with gold-finished metal rays and beveled center.",
    price: 799,
    category: "accessories",
    subcategory: "Mirrors",
    images: ["https://writingsonthewall.in/cdn/shop/products/Sunburst-Mirror-Writings-On-The-Wall-Wall-Mirror_40432939139351.jpg?v=1753288000"],
    features: ["Sunburst Design", "Gold Finish", "Beveled Mirror", "Statement Piece"],
    dimensions: { width: 36, height: 36, depth: 3, unit: "inches" },
    materials: ["Metal", "Beveled Mirror"],
    colors: ["Gold", "Silver", "Bronze"],
    inStock: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 67,
  },
  {
    id: "luxury-throw-pillows",
    name: "Luxury Throw Pillow Set",
    slug: "luxury-throw-pillow-set",
    description: "Set of four luxury throw pillows with different textures and premium fabrics.",
    price: 299,
    category: "accessories",
    subcategory: "Decorative Objects",
    images: ["https://shop.gkwretail.com/cdn/shop/products/CushionCoverVelvet150TCCushionCover-2_f9dc25ef-57df-4854-9c1c-6eafcc6989c7.jpg?v=1629008333"],
    features: ["Set of 4", "Mixed Textures", "Premium Fabrics", "Hidden Zippers"],
    dimensions: { width: 20, height: 20, depth: 6, unit: "inches" },
    materials: ["Velvet", "Linen", "Faux Fur", "Cotton"],
    colors: ["Neutral Tones", "Jewel Tones", "Monochrome"],
    inStock: true,
    rating: 4.5,
    reviewCount: 143,
  },
  {
    id: "pendant-light-set",
    name: "Modern Pendant Light Set",
    slug: "modern-pendant-light-set",
    description: "Set of three geometric pendant lights with adjustable cord lengths.",
    price: 899,
    category: "accessories",
    subcategory: "Lighting",
    images: ["https://m.media-amazon.com/images/I/61bCKDZ1tlL._UF1000,1000_QL80_.jpg"],
    features: ["Set of 3", "Geometric Design", "Adjustable Cords", "Dimmable LED"],
    dimensions: { width: 12, height: 18, depth: 12, unit: "inches" },
    materials: ["Brushed Metal", "Glass", "LED Bulbs"],
    colors: ["Brass", "Black", "Chrome"],
    inStock: true,
    isNew: true,
    rating: 4.6,
    reviewCount: 54,
  },
  {
    id: "abstract-wall-art",
    name: "Abstract Canvas Art Set",
    slug: "abstract-canvas-art-set",
    description: "Set of three abstract canvas prints with modern black and white design.",
    price: 399,
    category: "accessories",
    subcategory: "Artwork",
    images: ["https://m.media-amazon.com/images/I/61W+oeI2iTL._UF1000,1000_QL80_.jpg"],
    features: ["Set of 3", "Canvas Prints", "Ready to Hang", "Modern Design"],
    dimensions: { width: 24, height: 36, depth: 2, unit: "inches" },
    materials: ["Canvas", "Wood Frame"],
    colors: ["Black & White", "Sepia", "Blue Tones"],
    inStock: true,
    rating: 4.4,
    reviewCount: 128,
  },
]

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((product) => product.category === categorySlug)
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((product) => product.slug === slug)
}

export function getFeaturedProducts(): Product[] {
  return products.filter((product) => product.isFeatured)
}

export function getNewProducts(): Product[] {
  return products.filter((product) => product.isNew)
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((category) => category.slug === slug)
}
